# generated by datamodel-codegen:
#   filename:  diag_report.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, conint


class DiagCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    ok: bool
    details: Optional[str] = None


class DiagCache(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    path: str
    exists: bool
    sizeBytes: conint(ge=0)
    entries: conint(ge=0)
    rebuilt: bool
    error: Optional[str] = None


class DiagMigrationRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: conint(ge=1)
    title: str


class DiagConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exists: bool
    path: str
    current: Optional[conint(ge=0)] = None
    actual: Optional[conint(ge=0)] = None
    fingerprint: Optional[str] = None
    applied: Optional[list[DiagMigrationRef]] = None
    pending: Optional[list[DiagMigrationRef]] = None
    sections: Optional[list[str]] = None
    error: Optional[str] = None


class DiagEnv(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    python: str
    platform: str
    cwd: str


class DiagReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: conint(ge=1)
    tool_version: str
    root: str
    config: DiagConfig
    contexts: list[str]
    cache: DiagCache
    checks: list[DiagCheck]
    env: DiagEnv
