# generated by datamodel-codegen:
#   filename:  mode_sets_list.schema.json

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class Mode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier of the mode within the mode set
    """
    title: str
    """
    Human-readable title of the mode
    """
    description: Optional[str] = None
    """
    Optional detailed description of the mode
    """
    tags: Optional[list[str]] = None
    """
    Array of tags activated by this mode
    """
    options: Optional[dict[str, Any]] = None
    """
    Additional options specific to this mode
    """
    runs: Optional[dict[str, str]] = None
    """
    Provider-specific run commands mapping provider_id to command string
    """


class ModeSet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier of the mode set
    """
    title: str
    """
    Human-readable title of the mode set
    """
    modes: list[Mode]
    integration: Optional[bool] = None
    """
    True if this mode-set is an integration type (has runs)
    """


class ModeSetsList(BaseModel):
    """
    Response schema for 'list mode-sets' command
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    mode_sets: list[ModeSet] = Field(..., alias='mode-sets')
