# generated by datamodel-codegen:
#   filename:  sections_list.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Mode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier of the mode within the mode set
    """
    title: str
    """
    Human-readable title of the mode
    """
    description: Optional[str] = None
    """
    Optional detailed description of the mode
    """
    tags: Optional[list[str]] = None
    """
    Array of tags activated by this mode
    """
    runs: Optional[dict[str, str]] = None
    """
    Provider-specific run commands mapping provider_id to command string
    """


class Tag(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier of the tag within the tag set
    """
    title: str
    """
    Human-readable title of the tag
    """
    description: Optional[str] = None
    """
    Optional detailed description of the tag
    """


class ModeSet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier of the mode set
    """
    title: str
    """
    Human-readable title of the mode set
    """
    modes: list[Mode]
    integration: Optional[bool] = None
    """
    True if this mode-set is an integration type (has runs)
    """


class TagSet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier of the tag set
    """
    title: str
    """
    Human-readable title of the tag set
    """
    tags: list[Tag]


class SectionInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    """
    Section canonical name
    """
    mode_sets: list[ModeSet] = Field(..., alias='mode-sets')
    """
    Mode sets after extends resolution (may be empty)
    """
    tag_sets: list[TagSet] = Field(..., alias='tag-sets')
    """
    Tag sets after extends resolution (may be empty)
    """


class SectionsList(BaseModel):
    """
    Response schema for 'list sections' command
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    sections: list[SectionInfo]
